version: '2'
services:
  config:
    image: utsman/spring-cloud-market-sample-config-server
    restart: always
    ports:
      - 8888:8888

  discovery:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
    image: utsman/spring-cloud-market-sample-discovery-server
    restart: always
    ports:
      - 8761:8761

  statistics-service:
    environment:
      JAVA_OPTS: "-Xmx256m -Xms256m"
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: docker
    image: utsman/spring-cloud-market-sample-statistics-service
    restart: always
    ports:
      - 9000:9000

  edge:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_PROFILES_ACTIVE: docker
    image: utsman/spring-cloud-market-sample-edge-server
    restart: always
    ports:
      - 8765:8765