version: '2'
services:
  config-server:
    image: utsman/spring-cloud-market-sample-config-server
    restart: always
    ports:
      - 8888:8888

  discovery-server:
    image: utsman/spring-cloud-market-sample-discovery-server
    restart: always
    ports:
      - 8761:8761
    command: ["/app/bin/wait-for-it.sh", "-s", "-t", "120", "config-server:8888", "--", "./run.sh"]
    depends_on:
      - config-server
    extends:
      file: base.yml
      service: base

  statistics-service:
    environment:
      JAVA_OPTS: "-Xmx256m -Xms256m"
    image: utsman/spring-cloud-market-sample-statistics-service
    restart: always
    ports:
      - 9000:9000
    command: ["/app/bin/wait-for-it.sh", "-s", "-t", "120", "edge-server:8765", "--", "./run.sh"]
    depends_on:
      - edge-server
    extends:
      file: base.yml
      service: base

  edge-server:
    image: utsman/spring-cloud-market-sample-edge-server
    restart: always
    ports:
      - 8765:8765
    command: ["/app/bin/wait-for-it.sh", "-s", "-t", "120", "discovery-server:8761", "--", "./run.sh"]
    depends_on:
      - discovery-server
    extends:
      file: base.yml
      service: base

  monitor:
    image: utsman/spring-cloud-market-sample-monitor
    restart: always
    ports:
      - 9999:9999
    command: ["/app/bin/wait-for-it.sh", "-s", "-t", "120", "edge-server:8765", "--", "./run.sh"]
    depends_on:
      - edge-server
    extends:
      file: base.yml
      service: base