server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    statistics-service:
      path: /statistics/**
      serviceId: statistics-service